using SpotifyAPI.Web;
using tracksByPopularity.Application.Interfaces;
using tracksByPopularity.Domain.Enums;
using tracksByPopularity.Domain.Services;
using tracksByPopularity.Infrastructure.Helpers;

namespace tracksByPopularity.Application.Services;

/// <summary>
/// Application service implementation for creating playlists based on audio features.
/// Retrieves user tracks, fetches their audio features in batches, categorizes them by mood,
/// and creates corresponding playlists.
/// </summary>
public class AudioFeaturesPlaylistService : IAudioFeaturesPlaylistService
{
    private readonly ITrackService _trackService;
    private readonly ITrackMoodAnalyzerService _moodAnalyzer;
    private readonly IPlaylistService _playlistService;
    private readonly ILogger<AudioFeaturesPlaylistService> _logger;

    public AudioFeaturesPlaylistService(
        ITrackService trackService,
        ITrackMoodAnalyzerService moodAnalyzer,
        IPlaylistService playlistService,
        ILogger<AudioFeaturesPlaylistService> logger)
    {
        _trackService = trackService;
        _moodAnalyzer = moodAnalyzer;
        _playlistService = playlistService;
        _logger = logger;
    }

    public async Task<bool> GenerateMoodPlaylistsAsync(SpotifyClient spotifyClient)
    {
        _logger.LogInformation("Starting generation of mood playlists based on audio features");

        var allSavedTracks = await _trackService.GetAllUserTracksWithClientAsync(spotifyClient);
        if (!allSavedTracks.Any())
        {
            _logger.LogWarning("No saved tracks found in the user's library");
            return false;
        }

        var trackIds = allSavedTracks.Select(t => t.Track.Id).Where(id => !string.IsNullOrEmpty(id)).ToList();
        var categorizedTracks = new Dictionary<MoodCategory, List<string>>();
        
        foreach (MoodCategory mood in Enum.GetValues(typeof(MoodCategory)))
        {
            categorizedTracks[mood] = new List<string>();
        }

        // Spotify API limit for Audio Features is 100 tracks per request
        for (int i = 0; i < trackIds.Count; i += 100)
        {
            var batchIds = trackIds.Skip(i).Take(100).ToList();
            try
            {
                var request = new TracksAudioFeaturesRequest(batchIds);
                var featuresResponse = await spotifyClient.Tracks.GetSeveralAudioFeatures(request);

                foreach (var feature in featuresResponse.AudioFeatures)
                {
                    if (feature == null) continue;

                    var mood = _moodAnalyzer.AnalyzeMood(feature.Valence, feature.Energy);
                    if (mood.HasValue)
                    {
                        var trackUri = $"spotify:track:{feature.Id}";
                        categorizedTracks[mood.Value].Add(trackUri);
                    }
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed to retrieve audio features for a batch of tracks");
                return false;
            }
        }

        var userId = (await spotifyClient.UserProfile.Current()).Id;
        var userPlaylistsPage = await spotifyClient.Playlists.GetUsers(userId);
        var userPlaylists = await spotifyClient.PaginateAll(userPlaylistsPage);

        var success = true;

        foreach (var (mood, uris) in categorizedTracks)
        {
            if (!uris.Any()) continue;

            var playlistName = GetPlaylistNameForMood(mood);
            var playlistId = userPlaylists.FirstOrDefault(p => p.Name == playlistName)?.Id;

            try
            {
                if (playlistId == null)
                {
                    _logger.LogInformation("Creating new playlist: {PlaylistName}", playlistName);
                    var newPlaylist = await spotifyClient.Playlists.Create(userId, new PlaylistCreateRequest(playlistName)
                    {
                        Description = $"Generated by TracksByPopularity. Features {GetDescriptionForMood(mood)}",
                        Public = false
                    });
                    playlistId = newPlaylist.Id;
                }
                else
                {
                    _logger.LogInformation("Clearing existing playlist: {PlaylistName}", playlistName);
                    await _playlistService.RemoveAllTracksAsync(playlistId, spotifyClient);
                }

                _logger.LogInformation("Adding {Count} tracks to {PlaylistName}", uris.Count, playlistName);

                // Add in batches of 100
                if (playlistId != null)
                {
                    for (int i = 0; i < uris.Count; i += 100)
                    {
                        var batchUris = uris.Skip(i).Take(100).ToList();
                        await spotifyClient.Playlists.AddItems(playlistId, new PlaylistAddItemsRequest(batchUris));
                    }
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error processing playlist {PlaylistName}", playlistName);
                success = false;
            }
        }

        return success;
    }

    private string GetPlaylistNameForMood(MoodCategory mood) => mood switch
    {
        MoodCategory.HappyAndUpbeat => "Mood: Happy & Upbeat ☀️",
        MoodCategory.HighEnergy => "Mood: High Energy Workout ⚡",
        MoodCategory.ChillAndRelaxing => "Mood: Chill & Relaxing 🍃",
        MoodCategory.SadAndMelancholic => "Mood: Deep & Melancholic 🌧️",
        _ => "Mood: Unknown"
    };

    private string GetDescriptionForMood(MoodCategory mood) => mood switch
    {
        MoodCategory.HappyAndUpbeat => "High positivity and high energy tracks.",
        MoodCategory.HighEnergy => "High intensity and aggressive energy tracks.",
        MoodCategory.ChillAndRelaxing => "Relaxing, acoustic, and chill tracks.",
        MoodCategory.SadAndMelancholic => "Darker, slower, and melancholic tracks.",
        _ => ""
    };
}
